name: Deploy CSER

on:
  push:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          echo "Runner funcionando"
          hostname
          whoami
          cd /var/www/cser
          pwd
          git pull
